### PR TITLE
some minor fixes, and also, some major ones.

### PR DESCRIPTION
**Pull request by samebchase**
Hello Ralt,

Please take a look at the modifications.

We can discuss this further.

Samuel

### CODE REVIEW

**Comment by ralt** [comment]
Woah. Amazing content.

Just one nitpick: why did you delete the "Introduction" slide?

I'll definitely merge this though.

**Comment by samebchase** [comment]
Hello Ralt,

I thought that the Introduction slide could be merged with the Home slide. I mean, in terms, of resources, there wasn't much on that slide.

Consider using the same pattern, i.e. background image for all the slides. I think that it will be more uniform that way. Also, increasing the separation between each item (the `<dt>` and the `<dd>`) will enhance readability. I feel they are too close to each other now.

In terms of content, everything has a one-line description. These could surely be expanded upon in the future.

What other things do you want to add to the glossary? I'm sure more could be added here, but I can't think of any at the moment.

A Recommended Libraries section might be a good idea as well. The page on CLiki lists a lot of old, unmaintained libraries.

Samuel

**Comment by ralt** [comment]
Hi Samuel,

To be honest, the different background per slide is there to make sure each slide is clearly recognized from another.

I still need to work on the CSS. Notably, the DD/DT haven't been stylized very much.

The one-line descriptions are kind of there on purpose: this should be a quick introduction to explain what is what; no more. 2-3 lines could be acceptable though, I guess.

About the glossary... I couldn't think of anything either. Anything is welcome. Maybe some commonly used acronyms in the Lisp world?

The thing about "Recommended Libraries" is that it might become opinionated quite quickly, and very arguable. Although I guess this kind of list could work:
- cl-ppcre
- hunchentoot
- alexandria
- drakma
- bordeaux thread
- restas? weblocks? this is where it gets tricky. Maybe these shouldn't be included.

I guess it could be done since I made a nice list very quickly.

By the way, I'll make sure to add a "Contributors" section with your name on it seeing the hard work you provided. Thanks a lot for it!

Side note: if you add/remove sections, can you think about updating the menu too? :-)

**Comment by samebchase** [comment]
Oh. I updated the menu in my local copy. It think it's a git mess up on my part.

Now I'm beginning to reconsider having a recommended libraries section. I guess people can join `#lisp` and ask for themselves.

What some sites do, is, instead of subtle changes in background colour, there are more pronounced/colourful changes. Hmm...

**Comment by samebchase** [comment]
Okay. Now I understand why you want different backgrounds. All this while I was using the menu to navigate. Scrolling down with every slide having the same background looks weird.

**Comment by ralt** [comment]
Yeah, there are 2 features I want to add:
- Smooth scroll
- Menu trail

Once they'll be in, the backgrounds will make even more sense.

Btw, adding `#lisp` could be a good idea, but I'm not sure I should add it. Why not add reddit.com/r/lisp, planetlisp, etc then?

**Comment by samebchase** [comment]
I meant to say, people who want to find out which library to use, can join `#lisp` and ask for recommendations.

**Comment by samebchase** [comment]
Unrelated, but I put [this](http://www.codesurfers.net/links.html) up yesterday. Content is mine, friend's design.

**Comment by samebchase** [comment]
Okay then Ralt, I'll be off for today. If there's anything let me know.

Cheers,
Samuel

**Comment by ralt** [comment]
Heh, thanks for your commits already :-)

I'll have to merge it and clean it up a bit, the indentation is a bit fucked up :-)

**Comment by samebchase** [comment]
Cool.

**Comment by ralt** [comment]
Everything is merged and pushed :-) Thanks a lot!

**Comment by samebchase** [comment]
:-)

**Pull request merged**
