### PR TITLE
Added some sections and some links.

### PR DESCRIPTION
**Pull request by samebchase**
Hello Ralt,

We can reorganise the sections, if you want.

I just thought it would be better to separate the full Books from the tutorials.

Samuel

### CODE REVIEW

**Comment by ralt** [comment]
I think the glossary should be first. Introduce the vocabulary to people before telling them off.

**Comment by samebchase** [comment]
Hello Ralt,

What shall I add/remove to get this merged in?

Samuel

**Comment by ralt** [comment]
@samebchase I'm sorry, I'm not motivated to maintain this anymore. I've added you as maintainer of this repo, so the URL still exists, and you can merge the code yourself.

If you think the domain might be of some use somewhere, don't hesitate to tell me about it, I'll think about eventually transfering it.

**Comment by samebchase** [comment]
Hello Ralt,

Please see the email I sent you.

Samuel

**Pull request closed without merging**
